### PR TITLE
Add Radon to 1.18 & 1.16

### PR DESCRIPTION
**Pull request by Dakedres**
Radon has stable releases for 1.16 and 1.18.

It's weird that it launches fine with Starlight installed, it really doesn't feel like a good idea.

### CODE REVIEW

**Comment by NBZion** [comment]
as of the updates for starlight(forge) and starlight x create, it IS compatible with create thus far starting in the 1.01 release!

**Comment by Dakedres** [comment]
This PR isn't supposed to do with anything concerning Starlight and Create, if you look at the other PR I've made you will see there's a link to a relevant issue on the Starlight repo, which persists in 1.0.1

**Comment by lrmtheboss** [comment]
> as of the updates for starlight(forge) and starlight x create, it IS compatible with create thus far starting in the 1.01 release!

could you please link relevant documentation to prove that and move the discussion to PR #77

**Comment by lrmtheboss** [comment]
closes #79

**Pull request merged**
