### PR TITLE
Specify Starlight & Create incompatability

### PR DESCRIPTION
**Pull request by Dakedres**
https://github.com/PaperMC/Starlight/issues/136

Starlight x Create is not updated (atleast yet)

### CODE REVIEW

**Comment by Raft08** [comment]
I don't get any issue with Starlight and Create

**Comment by Dakedres** [comment]
Read the issue I linked. It happens when you have a mechanical piston extending downwards. I've tested it myself, it crashes.

**Comment by Raft08** [comment]
Just tested game crashed

**Comment by lrmtheboss** [comment]
looks good, but can you confirm if this issue is present on other versions like 1.17?

**Pull request merged**
